Add support for martha_v3 [WA-320]
DataBiosphere/terra-notebook-utils pull request #117
Opened 2020-09-18 20:06 UTC by salonishah11

This PR adds support for `martha_v3`. DRS methods will be able to ping v3 by default. If one would like to use `martha_v2` to resolve their DRS urls, they can override the default by running 
`export MARTHA_URL_VERSION=martha_v2`.

Closes https://broadworkbench.atlassian.net/browse/WA-320

2020-09-18 21:02 UTC, kshakir commented on tests/test_terra_notebook_utils.py
> +@testmode("dev_env_access")
Move above testing-in-prod. One should be testing in dev first.

2020-09-18 21:02 UTC, kshakir commented on tests/test_terra_notebook_utils_cli.py
> +class TestTerraNotebookUtilsCLI_DRSInDev(_CLITestCase):
🆙 ⬆️ 🔼
test in dev goes first

2020-09-21 17:05 UTC, xbrianh requested changes
Thank you very much for your contribution! This looks good overall, although there are a few minor issues to address. Please see comments.

2020-09-22 15:42 UTC, salonishah11 commented on terra_notebook_utils/drs.py
> +                       updated=data_object.get('updated', None))
Today I Learned! Thank you!

2020-09-22 16:05 UTC, salonishah11 commented on terra_notebook_utils/drs.py
> +            raise Exception(f"No GCS url found for DRS uri '{drs_url}'")
That's a good idea! But I am not sure what to put inside `except DRSResuolutionError:` block? Do we add extra logging information that could be helpful for debugging? Or did you have something else on mind?

2020-09-22 17:05 UTC, xbrianh commented on terra_notebook_utils/drs.py
> +            raise Exception(f"No GCS url found for DRS uri '{drs_url}'")
Unless exceptions requires special handling, or extra information, it is common to define them with with bare blocks. The custom exception will appear in stack traces, so I don't think it's necessary to add logging.

It is possible for users to catch and log exceptions if they wish.

Sometimes it's helpful to see examples from other libraries, such as in [Google's Python client](https://github.com/googleapis/python-api-core/blob/11d2097b9c125201244836261ae8068a32553586/google/api_core/exceptions.py). You can see that many are empty wrappers around base classes, while others just add small bits of information. hth!

2020-09-23 22:37 UTC, kshakir approved these changes

2020-09-25 00:55 UTC, kshakir commented on terra_notebook_utils/drs.py
> +                   name=None,  # currently martha_v3 doesn't return the file name. This should be changed in WA-348.
FYI- WA-344 is merged, so WA-348 is unblocked if you want to put it in progress and incorporate it into this PR. Or a separate PR works too if this one is close to merging.

2020-09-25 21:20 UTC, salonishah11 commented
@kshakir @xbrianh This PR is now ready for review! It now also extracts `fileName` key that `martha_v3` returns in response ([WA-348](https://broadworkbench.atlassian.net/browse/WA-348)).

2020-09-26 00:48 UTC, kshakir approved these changes

2020-09-26 00:48 UTC, kshakir commented on tests/test_terra_notebook_utils.py
> +        self.assertEqual(info.name, "hapmap_3.3.hg38.vcf.gz")
🥇

2020-09-28 15:10 UTC, rsasch approved these changes
small nits, otherwise 👍

2020-09-28 15:10 UTC, rsasch commented on README.md
> +- follow the setup instructions as mentioned in `Tests` section above for env Prod. Make sure you have access
nit:
```suggestion
- follow the setup instructions as mentioned in `Tests` section above for env Prod; make sure you have access 
```

2020-09-28 18:00 UTC, xbrianh approved these changes

2020-09-28 18:58 UTC, merged